/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnerRouteImport } from './routes/learner'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as LearnerProfileRouteImport } from './routes/learner.profile'
import { Route as LearnerDashboardRouteImport } from './routes/learner.dashboard'
import { Route as InstructorSettingsRouteImport } from './routes/instructor.settings'
import { Route as InstructorSessionsRouteImport } from './routes/instructor.sessions'
import { Route as CoordinatorSettingsRouteImport } from './routes/coordinator.settings'
import { Route as CoordinatorAlertsRouteImport } from './routes/coordinator.alerts'

const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerProfileRoute = LearnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LearnerRoute,
} as any)
const InstructorSettingsRoute = InstructorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorSessionsRoute = InstructorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => InstructorRoute,
} as any)
const CoordinatorSettingsRoute = CoordinatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorAlertsRoute = CoordinatorAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => CoordinatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/learner': typeof LearnerRouteWithChildren
  '/coordinator/alerts': typeof CoordinatorAlertsRoute
  '/coordinator/settings': typeof CoordinatorSettingsRoute
  '/instructor/sessions': typeof InstructorSessionsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/profile': typeof LearnerProfileRoute
}
export interface FileRoutesByTo {
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/learner': typeof LearnerRouteWithChildren
  '/coordinator/alerts': typeof CoordinatorAlertsRoute
  '/coordinator/settings': typeof CoordinatorSettingsRoute
  '/instructor/sessions': typeof InstructorSessionsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/profile': typeof LearnerProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/learner': typeof LearnerRouteWithChildren
  '/coordinator/alerts': typeof CoordinatorAlertsRoute
  '/coordinator/settings': typeof CoordinatorSettingsRoute
  '/instructor/sessions': typeof InstructorSessionsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/profile': typeof LearnerProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/coordinator'
    | '/instructor'
    | '/learner'
    | '/coordinator/alerts'
    | '/coordinator/settings'
    | '/instructor/sessions'
    | '/instructor/settings'
    | '/learner/dashboard'
    | '/learner/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/coordinator'
    | '/instructor'
    | '/learner'
    | '/coordinator/alerts'
    | '/coordinator/settings'
    | '/instructor/sessions'
    | '/instructor/settings'
    | '/learner/dashboard'
    | '/learner/profile'
  id:
    | '__root__'
    | '/coordinator'
    | '/instructor'
    | '/learner'
    | '/coordinator/alerts'
    | '/coordinator/settings'
    | '/instructor/sessions'
    | '/instructor/settings'
    | '/learner/dashboard'
    | '/learner/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoordinatorRoute: typeof CoordinatorRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/profile': {
      id: '/learner/profile'
      path: '/profile'
      fullPath: '/learner/profile'
      preLoaderRoute: typeof LearnerProfileRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/learner/dashboard': {
      id: '/learner/dashboard'
      path: '/dashboard'
      fullPath: '/learner/dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/instructor/settings': {
      id: '/instructor/settings'
      path: '/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/sessions': {
      id: '/instructor/sessions'
      path: '/sessions'
      fullPath: '/instructor/sessions'
      preLoaderRoute: typeof InstructorSessionsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/coordinator/settings': {
      id: '/coordinator/settings'
      path: '/settings'
      fullPath: '/coordinator/settings'
      preLoaderRoute: typeof CoordinatorSettingsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/alerts': {
      id: '/coordinator/alerts'
      path: '/alerts'
      fullPath: '/coordinator/alerts'
      preLoaderRoute: typeof CoordinatorAlertsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
  }
}

interface CoordinatorRouteChildren {
  CoordinatorAlertsRoute: typeof CoordinatorAlertsRoute
  CoordinatorSettingsRoute: typeof CoordinatorSettingsRoute
}

const CoordinatorRouteChildren: CoordinatorRouteChildren = {
  CoordinatorAlertsRoute: CoordinatorAlertsRoute,
  CoordinatorSettingsRoute: CoordinatorSettingsRoute,
}

const CoordinatorRouteWithChildren = CoordinatorRoute._addFileChildren(
  CoordinatorRouteChildren,
)

interface InstructorRouteChildren {
  InstructorSessionsRoute: typeof InstructorSessionsRoute
  InstructorSettingsRoute: typeof InstructorSettingsRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorSessionsRoute: InstructorSessionsRoute,
  InstructorSettingsRoute: InstructorSettingsRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface LearnerRouteChildren {
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearnerProfileRoute: typeof LearnerProfileRoute
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerProfileRoute: LearnerProfileRoute,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CoordinatorRoute: CoordinatorRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
